In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import os

In [2]:
df = pd.read_csv('/Users/lyw/baseline/train/train.csv')#,index=False)
df

,leaktype,0HZ,10HZ,20HZ,30HZ,40HZ,50HZ,60HZ,70HZ,80HZ,...,5030HZ,5040HZ,5050HZ,5060HZ,5070HZ,5080HZ,5090HZ,5100HZ,5110HZ,5120HZ
0,out,0,2,2,0,2,0,2,2,2,...,2,5,2,2,5,2,2,5,2,5
1,out,0,0,0,3,0,3,0,0,0,...,0,3,3,3,3,3,3,3,3,6
2,out,0,4,4,4,4,5,4,4,5,...,5,5,6,5,6,6,6,5,6,4
3,out,0,6,5,5,6,5,6,6,5,...,6,6,7,7,5,6,5,5,7,7
4,out,0,3,0,0,3,0,0,3,3,...,3,3,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33595,noise,0,5,6,6,23,15,7,10,15,...,8,7,7,7,7,7,6,7,6,7
33596,noise,0,3,3,3,2,3,3,3,3,...,3,5,5,5,5,3,3,3,3,3
33597,noise,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,3,0,0,3
33598,noise,0,8,7,7,5,8,8,8,8,...,8,10,8,8,10,10,7,7,7,5
33599,noise,0,0,3,3,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33600 entries, 0 to 33599
Columns: 514 entries, leaktype to 5120HZ
dtypes: int64(513), object(1)
memory usage: 131.8+ MB

In [4]:
df.describe()

,0HZ,10HZ,20HZ,30HZ,40HZ,50HZ,60HZ,70HZ,80HZ,90HZ,...,5030HZ,5040HZ,5050HZ,5060HZ,5070HZ,5080HZ,5090HZ,5100HZ,5110HZ,5120HZ
count,33600.0,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,...,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000,33600.000000
mean,0.0,4.751250,5.045565,5.392768,5.628333,5.880238,11.479196,6.243304,6.619375,7.391488,...,6.607411,6.571964,6.567560,6.557649,6.548006,6.557411,6.532351,6.512440,6.499881,6.497976
std,0.0,4.645084,5.618080,6.809801,7.466011,8.369581,61.216484,7.926678,8.094238,10.250893,...,6.073526,5.990836,5.981968,5.947658,5.912425,5.963627,5.865515,5.814981,5.819533,5.799409
min,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.0,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
50%,0.0,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,...,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000
75%,0.0,5.000000,5.000000,5.000000,5.000000,5.000000,6.000000,6.000000,6.000000,7.000000,...,7.000000,7.000000,6.000000,7.000000,7.000000,7.000000,6.000000,7.000000,6.000000,6.000000
max,0.0,83.000000,146.000000,125.000000,196.000000,251.000000,1221.000000,123.000000,186.000000,438.000000,...,119.000000,92.000000,96.000000,101.000000,83.000000,92.000000,83.000000,94.000000,88.000000,81.000000

In [5]:
df_o=df[df['leaktype']=='out']
df_o

,leaktype,0HZ,10HZ,20HZ,30HZ,40HZ,50HZ,60HZ,70HZ,80HZ,...,5030HZ,5040HZ,5050HZ,5060HZ,5070HZ,5080HZ,5090HZ,5100HZ,5110HZ,5120HZ
0,out,0,2,2,0,2,0,2,2,2,...,2,5,2,2,5,2,2,5,2,5
1,out,0,0,0,3,0,3,0,0,0,...,0,3,3,3,3,3,3,3,3,6
2,out,0,4,4,4,4,5,4,4,5,...,5,5,6,5,6,6,6,5,6,4
3,out,0,6,5,5,6,5,6,6,5,...,6,6,7,7,5,6,5,5,7,7
4,out,0,3,0,0,3,0,0,3,3,...,3,3,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,out,0,3,4,3,4,4,4,4,4,...,4,4,4,4,4,4,5,5,4,4
1796,out,0,5,4,5,5,5,5,5,6,...,6,7,7,8,7,7,7,7,7,6
1797,out,0,2,2,2,2,2,2,2,4,...,2,4,2,2,4,2,2,2,2,4
1798,out,0,2,0,2,0,2,0,2,0,...,2,2,2,2,2,2,2,2,2,2
1799,out,0,37,37,43,46,50,50,52,49,...,14,12,11,11,12,12,12,12,9,12

In [6]:
df_o = df_o.T
df_o

,0,1,2,3,4,5,6,7,8,9,...,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799
leaktype,out,out,out,out,out,out,out,out,out,out,...,out,out,out,out,out,out,out,out,out,out
0HZ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10HZ,2,0,4,6,3,4,4,3,13,11,...,2,5,4,2,3,3,5,2,2,37
20HZ,2,0,4,5,0,4,4,3,10,11,...,2,5,4,2,3,4,4,2,0,37
30HZ,0,3,4,5,0,4,4,3,11,11,...,2,4,4,2,3,3,5,2,2,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5080HZ,2,3,6,6,3,4,6,5,19,15,...,2,10,5,4,5,4,7,2,2,12
5090HZ,2,3,6,5,3,5,7,5,19,15,...,2,11,5,4,5,5,7,2,2,12
5100HZ,5,3,5,5,3,5,5,3,17,17,...,2,10,5,4,5,5,7,2,2,12
5110HZ,2,3,6,7,3,5,6,5,16,13,...,2,9,6,2,5,4,7,2,2,9
5120HZ,5,6,4,7,3,5,7,3,16,15,...,2,7,5,4,5,4,6,4,2,12

In [7]:
df_o = df_o.drop(['0HZ'], axis=0)
df_o

,0,1,2,3,4,5,6,7,8,9,...,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799
leaktype,out,out,out,out,out,out,out,out,out,out,...,out,out,out,out,out,out,out,out,out,out
10HZ,2,0,4,6,3,4,4,3,13,11,...,2,5,4,2,3,3,5,2,2,37
20HZ,2,0,4,5,0,4,4,3,10,11,...,2,5,4,2,3,4,4,2,0,37
30HZ,0,3,4,5,0,4,4,3,11,11,...,2,4,4,2,3,3,5,2,2,43
40HZ,2,0,4,6,3,5,4,3,14,12,...,2,3,2,2,3,4,5,2,0,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5080HZ,2,3,6,6,3,4,6,5,19,15,...,2,10,5,4,5,4,7,2,2,12
5090HZ,2,3,6,5,3,5,7,5,19,15,...,2,11,5,4,5,5,7,2,2,12
5100HZ,5,3,5,5,3,5,5,3,17,17,...,2,10,5,4,5,5,7,2,2,12
5110HZ,2,3,6,7,3,5,6,5,16,13,...,2,9,6,2,5,4,7,2,2,9
5120HZ,5,6,4,7,3,5,7,3,16,15,...,2,7,5,4,5,4,6,4,2,12

In [8]:
a = np.asarray(df_o)
a

array([['out', 'out', 'out', ..., 'out', 'out', 'out'],
       [2, 0, 4, ..., 2, 2, 37],
       [2, 0, 4, ..., 2, 0, 37],
       ...,
       [5, 3, 5, ..., 2, 2, 12],
       [2, 3, 6, ..., 2, 2, 9],
       [5, 6, 4, ..., 4, 2, 12]], dtype=object)

In [9]:
a = np.delete(a,0,axis=0)
a

array([[2, 0, 4, ..., 2, 2, 37],
       [2, 0, 4, ..., 2, 0, 37],
       [0, 3, 4, ..., 2, 2, 43],
       ...,
       [5, 3, 5, ..., 2, 2, 12],
       [2, 3, 6, ..., 2, 2, 9],
       [5, 6, 4, ..., 4, 2, 12]], dtype=object)

In [11]:
a = list(a)

In [18]:
np.shape(a)

(512, 1800)

In [ ]:
df_i=df[df['leaktype']=='in']
df_i

In [ ]:
df_n=df[df['leaktype']=='normal']
df_n

In [ ]:
df_no=df[df['leaktype']=='noise']
df_no

In [ ]:
df_ot=df[df['leaktype']=='other']
df_ot

In [ ]:
df_o.describe()

In [ ]:
df_i.describe()

In [ ]:
df_n.describe()

In [ ]:
df_no.describe()

In [ ]:
df_ot.describe()

In [ ]:
#pd.describe_option()

In [ ]:
#!pip install stemgraphic

In [ ]:
import stemgraphic

In [ ]:
stemgraphic.stem_graphic(df_o['10HZ'])

In [ ]:
df_o = df_o.drop(['0HZ'], axis=1)
df_o

In [ ]:
df_i = df_i.drop(['0HZ'], axis=1)
df_i

In [ ]:
df_n = df_n.drop(['0HZ'], axis=1)
df_n

In [ ]:
df_no = df_no.drop(['0HZ'], axis=1)
df_no

In [ ]:
df_ot = df_ot.drop(['0HZ'], axis=1)
df_ot

In [ ]:
pd.DataFrame(df_o.values).plot.hist()

In [ ]:
#df_o = df_o.T
#print(df_o)

In [ ]:
#pd.DataFrame(df_o.values).plot.hist()

In [ ]:
# sns.pairplot(df_o)

In [ ]:
# sns.heatmap(df_o.corr(), annot=True,
#            fmt = '.3g', vmin=-1, vmax=1, center=0, cmap='Spectral', linewidths=1,
#            linecolor='black')

In [ ]:
# sns.heatmap(df_in.corr(), annot=True,
#            fmt = '.3g', vmin=-1, vmax=1, center=0, cmap='Spectral', linewidths=1,
#            linecolor='black')

In [ ]:
# sns.heatmap(df_n.corr(), annot=True,
#            fmt = '.3g', vmin=-1, vmax=1, center=0, cmap='Spectral', linewidths=1,
#            linecolor='black')

In [ ]:
# sns.heatmap(df_no.corr(), annot=True,
#            fmt = '.3g', vmin=-1, vmax=1, center=0, cmap='Spectral', linewidths=1,
#            linecolor='black')

In [ ]:
# sns.heatmap(df_ot.corr(), annot=True,
#            fmt = '.3g', vmin=-1, vmax=1, center=0, cmap='Spectral', linewidths=1,
#            linecolor='black')

In [ ]:
df_o.set_index('leaktype', inplace=True)
df_o

In [ ]:
#print(type(df_i))
#print(df_i)
#lst = [list(row) for row in tup1]

# df_i = [list(row) for row in df_i]
# print(df_i)

df_i.set_index('leaktype', inplace=True)
df_i

In [ ]:
df_n.set_index('leaktype', inplace=True)
df_n

In [ ]:
df_no.set_index('leaktype', inplace=True)
df_no

In [ ]:
df_ot.set_index('leaktype', inplace=True)
df_ot

In [ ]:
df_o.shape()

In [ ]:
print(df_o.T)

In [ ]:
df= df.T

In [ ]:
print(df_n)

In [ ]:
#!pip install sklearn

In [ ]:
#!conda install sklearn

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
#from keras.optimizers import SGD
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score, KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split


seed = 100
#numpy.random.seed(seed)

dataframe =df
dataset = dataframe.values
X_train= dataset
y_train = dataset
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train, y_train, test_size=0.2, random_state=42)

# encode class value as integers
# encoder = LabelEncoder()
# encoder.fit(y_train)#Y
# encoded_Y = encoder.transform(y_train) #y
# dummy_y = np_utils.to_categorical(encoded_Y)

def baseline_model():
    model = Sequential()
    model.add(Dense(4, input_dim=4, init='normal', activation='relu'))
    model.add(Dense(3, init='normal', activation='sigmoid'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

filepath="weights-improvement-{epoch:02d}-{val_acc:.2f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

estimator = KerasClassifier(build_fn=baseline_model, validation_split=0.33, nb_epoch=200, batch_size=5, callbacks=callbacks_list, verbose=0)
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X_train, y_train, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

In [ ]:
옥외누수(out), 옥내누수(in), 정상(normal), 전기/기계음(noise), 환경음(other)

In [ ]:
print(data.T)